name:                day6
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6.5.1
- text >= 1.2.4.1

library:
  source-dirs: src

executables:
  day6-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - day6

tests:
  day6-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - day6
    - test-framework >= 0.8.2
    - test-framework-hunit >= 0.3.0
    - HUnit >= 1.6.2
