name:                day24
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- vector >= 0.12
- containers >= 0.6.5.1
- mtl >= 2.2.0
- megaparsec >=9.0.0
- parallel >= 3

library:
  source-dirs: src

executables:
  day24-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - day24

tests:
  day24-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - day24
    - test-framework >= 0.8.2
    - test-framework-hunit >= 0.3.0
    - HUnit >= 1.6.2
